language: python
sudo: required
dist: trusty

python:
  - 2.7
  - 3.4
  - 3.5

install:
  - sudo apt-get install iverilog
  - pip install pytest pytest-pythonpath pyverilog

script:
  - python -m pytest .
